# fly.toml app configuration file generated for my-blog1 on 2024-07-09T19:59:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-blog1'
primary_region = 'mad'

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "8080"
  VITE_API_URL = "https://my-blog1.fly.dev/api"